### ISSUE TITLE
Issue-Optimise image processor

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/seo-blog-and-landingpage#13]
Automated Review Comments
Issues in eleventy.config.js:
  - (4, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')

**Comment by Py-Ec** [comment]
I got it.
