### ISSUE TITLE
Issue-Updated landing page template formatting

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/seo-blog-and-landingpage#23]
Automated Review Comments
Issues in views/index.liquid:
  - (7, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (138, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (164, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (167, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (179, 'Line exceeds 80 characters')
  - (180, 'Line exceeds 80 characters')
  - (181, 'Line exceeds 80 characters')
  - (183, 'Line exceeds 80 characters')
  - (184, 'Line exceeds 80 characters')

**Comment by Py-Ec** [comment]
I got it.
