### ISSUE TITLE
Issue-Fixed server based posts rendering issue

When posts were being fetched from the server, sometimes they wouldn't load

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/seo-blog-and-landingpage#25]
Automated Review Comments
Issues in eleventy.config.js:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (82, 'Hardcoded string found')

**Comment by Py-Ec** [comment]
I got it.
