### ISSUE TITLE
Issue-First commit

A starting point for SEO optimised landing page and blog built on 11ty and Tailwind CSS + DaisyUI

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/seo-blog-and-landingpage#4]
Automated Review Comments
Issues in assets/favicon/site.webmanifest:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in eleventy.config.js:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (165, 'Line exceeds 80 characters')
  - (165, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in postcss.config.js:
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in style/app.css:
  - (10, 'Line exceeds 80 characters')
Issues in tailwind.config.js:
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in views/404.liquid:
  - (16, 'Line exceeds 80 characters')
Issues in views/_data/blogSuperUseful.js:
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
Issues in views/_data/defaultSettings.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in views/_includes/core/foot.liquid:
  - (2, 'Hardcoded string found')
Issues in views/_includes/core/head.liquid:
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in views/_includes/footer.liquid:
  - (2, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
Issues in views/_includes/navbar.liquid:
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
Issues in views/_layouts/blog_post.liquid:
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
Issues in views/_layouts/landing.liquid:
  - (7, 'Hardcoded string found')
Issues in views/_layouts/main.liquid:
  - (6, 'Hardcoded string found')
Issues in views/blog.local.liquid:
  - (13, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
Issues in views/blog.server.liquid:
  - (13, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
Issues in views/blog/_super_useful_external_post.liquid:
  - (11, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')

**Comment by Py-Ec** [comment]
I got it.
